spring:
  datasource:
    url: jdbc:mysql://58.146.107.56:3306/one-to-many-unidirectional-db?createDatabaseIfNotExist=true&useSSL=false
    username: ankat
    password: $m@r7C@rd

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE