server:
  port: 0

spring:
  datasource:
    url: jdbc:mysql://192.168.0.111:3306/one-to-many-unidirectional-db?createDatabaseIfNotExist=true&useSSL=false
    username: ankat
    password: $m@r7C@rd

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
      generate-ddl: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE